[Docs] GitHub Actions
layer5io/docs pull request #106
Opened 2023-12-02 16:44 UTC by saurabh100ni

**Notes for Reviewers**

this is the updated work from previous [PR](https://github.com/meshery/meshery/pull/9515) raised in [Meshery Repository ](https://github.com/meshery/meshery).

This PR fixes #
[#9440](https://github.com/meshery/meshery/issues/9440)

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-12-09 12:47 UTC, leecalcote requested changes

2023-12-09 12:47 UTC, leecalcote commented on content/en/cloud/github-actions/_index.md
> +To initiate the GitOps workflow with Meshery, it is essential to [sign up](https://layer5.io/cloud-native-management/meshmap#:~:text=Signup%20for,MeshMap%20Beta) for MeshMap. MeshMap serves as a fund
This link ultimately lands visitors on the wrong section of th page.

2023-12-11 01:28 UTC, leecalcote commented on content/en/cloud/github-actions/_index.md
> +To initiate the GitOps workflow with Meshery, it is essential to [sign up](https://layer5.io/cloud-native-management/meshmap#:~:text=Signup%20for,MeshMap%20Beta) for MeshMap. MeshMap serves as a fund
Make sense?

2023-12-11 05:47 UTC, saurabh100ni commented on content/en/cloud/github-actions/_index.md
> +To initiate the GitOps workflow with Meshery, it is essential to [sign up](https://layer5.io/cloud-native-management/meshmap#:~:text=Signup%20for,MeshMap%20Beta) for MeshMap. MeshMap serves as a fund
Yes, it does. Fixing it.

2023-12-12 19:14 UTC, leecalcote commented on content/en/cloud/github-actions/_index.md
> +To initiate the GitOps workflow with Meshery, it is essential to [sign up](https://layer5.io/cloud-native-management/meshmap#:~:text=Signup%20for,MeshMap%20Beta) for MeshMap. MeshMap serves as a fund
@saurabh100ni, tell me how you fixed it and ask for review (again) if you're sure that its ready.

Do this as a general behavior, too.

2023-12-17 18:17 UTC, saurabh100ni commented on content/en/cloud/github-actions/_index.md
> +To initiate the GitOps workflow with Meshery, it is essential to [sign up](https://layer5.io/cloud-native-management/meshmap#:~:text=Signup%20for,MeshMap%20Beta) for MeshMap. MeshMap serves as a fund
@leecalcote For some reason web-page for [meshmap](https://layer5.io/cloud-native-management/meshmap#:~:text=Signup%20for,MeshMap%20Beta) is navigating to `COLLABORATE` section by default.
So, I redirected it to the same form on [play.meshery.io](https://play.meshery.io/).

2024-01-21 21:37 UTC, merged