Lunr local searcher implemented
layer5io/docs pull request #107
Opened 2023-12-04 18:58 UTC by iArchitSharma

With this PR Layer5 Docs shift to the built-in local search by Docsy i.e. **Lunr**

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-12-04 21:22 UTC, iArchitSharma commented
Thanks @leecalcote

2023-12-05 07:05 UTC, ritiksaxena124 commented
@iArchitSharma looks good. You see on hover over the title of the search results the text is not visible.

2023-12-05 14:47 UTC, leecalcote commented
Recently, I have added a new shortcut key to the search field.

2023-12-05 14:48 UTC, leecalcote requested changes
This PR overwrites the recent keyboard shortcut for search that I added.

2023-12-05 16:20 UTC, iArchitSharma commented
@leecalcote fixed

2023-12-05 17:34 UTC, leecalcote commented
@iArchitSharma thank you. Will you implement a clickaway for closing the search panel (clickaway and ESC might be nice, too)

2023-12-05 19:02 UTC, leecalcote commented on assets/scss/_search.scss
> +// Search
This CSS duplicates classes in the assets/scss/_styles_project.scss file. Will you de-duplicate and consolidate all search-related CSS into this file, @iArchitSharma?

2023-12-06 09:13 UTC, iArchitSharma commented on assets/scss/_search.scss
> +// Search
actually those search classes are used for styling different search bar as the search bar on top right side of nav is different than the search bar on the sidebar nav of docs.
by consolidating both of them on same will make them look same.

2023-12-07 23:00 UTC, leecalcote requested changes

2023-12-08 14:29 UTC, iArchitSharma commented on assets/scss/_search.scss
> +// Search
Done made the changes

2023-12-08 14:42 UTC, leecalcote requested changes
/ hotkey does not work/

2023-12-08 20:06 UTC, merged