[Docs] enhance: use flex layout for landing page cards
layer5io/docs pull request #156
Opened 2024-01-17 08:31 UTC by SamIsTheFBI

**Notes for Reviewers**

This PR fixes #76 

## :framed_picture:  Current Behavior

|![image](https://github.com/layer5io/docs/assets/70562711/86c485af-5b4c-4fb8-b311-05af21ba0cf4)|
|--|
|<div align="center"> **Before changes** </div>|
## :zap: New Behavior

|![image](https://github.com/layer5io/docs/assets/70562711/0c8f1731-db72-451e-94bd-579a5764ac8b)|
|--|
|<div align="center"> **After changes** </div>|

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-01-18 06:59 UTC, iArchitSharma commented
@SamIsTheFBI Thanks that looks good, can also fix th eimage like we have in figma :
![image](https://github.com/layer5io/docs/assets/74408634/34e3fa90-a4e0-4497-98ab-c7b6880527a7)

2024-01-18 08:12 UTC, leecalcote requested changes

2024-01-18 08:12 UTC, leecalcote commented on content/en/_index.md
> +<div class="box2">
@SamIsTheFBI thanks! 

Employ your imagination here for a better variable name.

2024-01-18 13:04 UTC, SamIsTheFBI commented
Hi @iArchitSharma could you tell me where I can get this figma file for reference?

2024-01-18 13:52 UTC, iArchitSharma commented
@SamIsTheFBI   https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=21084%3A6224&mode=design&t=fpzsSKW93n2kr9j0-1

2024-01-18 16:30 UTC, SamIsTheFBI commented
@iArchitSharma I have made some changes to make the forum card image look a lot like the one in Figma. Please check it.

Also, @leecalcote I changed some classnames. Please tell me if they're desirable.

2024-01-21 12:36 UTC, saurabh100ni commented
Hi @SamIsTheFBI ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

2024-01-21 19:23 UTC, leecalcote commented on assets/scss/_landing_project.scss
> +.hidden {
@SamIsTheFBI is this used anywhere?

2024-01-21 21:47 UTC, leecalcote commented
@iArchitSharma review this carefully. Make any changes necessary and merge.

2024-01-22 17:48 UTC, SamIsTheFBI commented on assets/scss/_landing_project.scss
> +.hidden {
oh right. I was using the `hidden` class as a console.log thing. I'd hide elements and try to figure out what's happening in the code.

This commit [0a93c93](https://github.com/layer5io/docs/pull/156/commits/0a93c933290ce073ca052563f327122759471c4a) removes it and any other comments.

2024-01-25 13:35 UTC, iArchitSharma approved these changes
LGTM thanks @SamIsTheFBI

2024-01-25 13:36 UTC, merged

2024-01-25 15:03 UTC, SamIsTheFBI commented
Okay @iArchitSharma  but how should I review it? Like, what am I supposed to do? I don't know what's the process in Github 😅