Fixed Home Page Responsiveness issue
layer5io/docs pull request #160
Opened 2024-01-20 19:04 UTC by Tushar-sahani

**Notes for Reviewers**

This PR fixes the issue #140 Home page Responsiveness. 

**Before**
![Screenshot 2024-01-08 111520](https://github.com/layer5io/docs/assets/104075614/e38b46a5-7a82-4c96-b844-d35bdf510d71)

**After**
![image](https://github.com/layer5io/docs/assets/104075614/305dd3c9-e60a-494f-94b1-d0c1f0f23b0f)

2024-01-21 12:34 UTC, saurabh100ni commented
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

2024-01-21 21:38 UTC, leecalcote commented
Thank you, @Tushar-sahani

2024-01-21 21:47 UTC, leecalcote commented
This PR needs to take into account PR https://github.com/layer5io/docs/pull/156

2024-01-22 04:32 UTC, 35C4n0r requested changes
@Tushar-sahani  I've left a few suggestions, please check them out.

2024-01-22 04:32 UTC, 35C4n0r commented on assets/scss/_styles_project.scss
> +    right: 13rem;
@Tushar-sahani tune the `right` value to be in the range `-45rem` to `-50rem`. This would help to keep the same design and feel as in the desktop view.

2024-01-22 04:32 UTC, 35C4n0r commented on assets/scss/_search.scss
> +  @media (max-width: 991.98px) {
Do we need to put `.td-navbar-nav-scroll` inside a breakpoint?
```suggestion
  .td-navbar-nav-scroll {
      max-width: fit-content;
    }
```

2024-01-22 04:32 UTC, 35C4n0r commented on assets/scss/_styles_project.scss
> +    font-size: 4rem;
We should centre align the text here, 
```suggestion
    font-size: 4rem;
    text-align: center;
```

2024-01-22 10:22 UTC, Tushar-sahani commented on assets/scss/_styles_project.scss
> +    right: 13rem;
I have made some changes in it please review it and suggest if it is ok or not.

2024-01-22 18:11 UTC, 35C4n0r approved these changes
LGTM, Good work @Tushar-sahani.

2024-01-23 05:03 UTC, leecalcote commented
@35C4n0r thanks much for this review. 👏

2024-01-23 14:21 UTC, iArchitSharma commented
@Tushar-sahani nice work can you please fix those images inside container
![image](https://github.com/layer5io/docs/assets/74408634/ac89b20b-7711-4720-b503-d3ad70ca4ad4)

2024-01-25 13:19 UTC, iArchitSharma commented
@ritiksaxena124 any suggestions?

2024-01-25 13:37 UTC, ritiksaxena124 commented
**Dimension: 375x667 (Iphone SE)**
1. Increase the padding below the nav items
![image](https://github.com/layer5io/docs/assets/51539117/5a1f26c9-a74e-4f88-883a-bb04eb2ec572)

2. Keep  the left and right padding constant throughout the page
![image](https://github.com/layer5io/docs/assets/51539117/cb180560-3d0c-40af-ad72-4f9529a9b669)

3. In mobile view all the buttons can have equal with
![image](https://github.com/layer5io/docs/assets/51539117/a9a20344-c0b9-4ad3-86c6-e818d57490ac)

4. The image is skewed
![image](https://github.com/layer5io/docs/assets/51539117/c5b8c62e-8ea7-47bb-8a8a-887647dbbd96)

5. Maintain the spacing between the card title and content
![image](https://github.com/layer5io/docs/assets/51539117/7214fe08-0291-4268-a197-c2873fc69dd6)

6. Keep the font size of content smaller than the title inside the card

**Dimension: 835x1285**
![image](https://github.com/layer5io/docs/assets/51539117/3f23da98-3e69-4f51-92d2-2bf045274446)


- Add the max-width to 1440px of the page


I guess enough suggestions for now 😉

2024-01-25 13:40 UTC, iArchitSharma commented
@Tushar-sahani, since #156 has been merged, there are some merge conflicts. Please resolve those before proceeding further.

2024-01-25 14:08 UTC, Tushar-sahani commented
> @Tushar-sahani, since #156 has been merged, there are some merge conflicts. Please resolve those before proceeding further.

ok 👍🏻

2024-01-25 20:03 UTC, Tushar-sahani commented
> @Tushar-sahani Below `width - 1536` the layout is not displaying as intended
> ![image](https://github.com/layer5io/docs/assets/74408634/0d59abc7-44f8-4096-853c-13ea7c0a62b1)
> 

This is because of the layout display properties charged in PR #156 from Grid to Flex.I will fix it.

2024-01-25 20:29 UTC, iArchitSharma commented
@Tushar-sahani, are you sure? Because I checked this before merging #156, and it was occurring at that time too.

2024-01-26 06:16 UTC, Tushar-sahani commented
Yes, @iArchitSharma you can check this issue on  https://docs.layer5.io/  in the above dimension in screenshot(1535x900) . This issue is not from my side.
![Screenshot 2024-01-26 113728](https://github.com/layer5io/docs/assets/104075614/6935a1db-d203-486f-b6b0-080d6f1caf21)

2024-01-26 08:43 UTC, iArchitSharma commented
@Tushar-sahani Oh, anyways, please fix this

2024-01-26 14:52 UTC, Tushar-sahani commented
@iArchitSharma please review the changes.

2024-01-26 17:49 UTC, iArchitSharma commented
@Tushar-sahani `992 * 656`
![image](https://github.com/layer5io/docs/assets/74408634/7d8f80a2-1ac2-42cc-a807-5136c6de4231)

2024-01-26 18:03 UTC, Tushar-sahani commented
@iArchitSharma ok, Needs some updates elsewhere??

2024-01-29 12:49 UTC, iArchitSharma commented
@Tushar-sahani have you made the changes asked by @ritiksaxena124 ?

2024-02-01 13:52 UTC, iArchitSharma commented
@Tushar-sahani Thanks you so much for this

2024-02-01 13:54 UTC, merged