Adding Labeler workflow
layer5io/docs pull request #188
Opened 2024-01-25 19:21 UTC by surajvast1

**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-01-26 20:36 UTC, hamza-mohd requested changes

2024-01-26 20:36 UTC, hamza-mohd commented on .github/labeler.yml
> +      - "content/en/meshmap/**/*"
Why are you labeling meshmap content with `component-cloud-docs`? Don't.

2024-01-26 20:36 UTC, hamza-mohd commented
Add `area/ci` for .github

2024-01-27 05:48 UTC, iArchitSharma requested changes

2024-01-27 06:30 UTC, surajvast1 commented on .github/labeler.yml
> +component/cloud-docs:
@iArchitSharma Sure I assumed both to be under a single label . 
I'll make the changes

2024-01-28 13:24 UTC, saurabh100ni commented
Hi @surajvast1  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

2024-01-29 12:29 UTC, surajvast1 commented
@iArchitSharma its updated and good to go

2024-01-31 08:50 UTC, iArchitSharma commented
@Yashsharma1911 can you please check if it works correctly ?

2024-02-02 06:10 UTC, leecalcote requested changes

2024-02-02 06:10 UTC, leecalcote commented on .github/labeler.yml
> +component/cloud-docs:
@surajvast1 don't include meshery-docs here. That is a separate site. Use meshmap for meshmap.

One more chance to get this right. If you don't this time time, let's close this PR and allow another contributor a turn.

2024-02-02 11:28 UTC, surajvast1 commented on .github/labeler.yml
> +component/cloud-docs:
@leecalcote I guess there is a lack of communication here . I implemented it correctly before but as @iArchitSharma ask me to add component/meshmap-docs i changed it . Its updated now

2024-02-26 15:54 UTC, surajvast1 commented
I have tested the labeler workflow at my end it works perfectly. 
Test1) Updating a random file inside a code not in the mentioned path so it doesnot adds labeler https://github.com/surajvast1/docs/pull/17/files

Test2) Updating a file in this path content/en/cloud so it again does not adds labeler 
https://github.com/surajvast1/docs/pull/18/files

Test3) Updating a file in the path content/en/meshmap/**/*  as mentioned in the error .So you can see labeler here 
https://github.com/surajvast1/docs/pull/19

Please consider it ,apologies for the miscommunication 😊.

2024-02-26 21:29 UTC, leecalcote commented
good deal. @iArchitSharma are we good to go?

2024-02-28 17:47 UTC, iArchitSharma commented
@surajvast1 the request was to add the meshmap label when the meshmap docs are edited and add the cloud label when cloud docs are edited. Your pull request only adds the 'cloud' labeler to both."

2024-02-28 18:08 UTC, iArchitSharma commented
@surajvast1 https://github.com/layer5io/docs/pull/224

2024-02-28 18:08 UTC, closed without merging

2024-02-28 18:55 UTC, surajvast1 commented
Now you have added meshery-docs. I hope it maches the requirements.Thanks I got to learn a lot working on this .

2024-02-29 05:52 UTC, iArchitSharma commented
@surajvast1 It is meshmap docs label which is different from meshery