added notification off docs
layer5io/docs pull request #196
Opened 2024-01-29 14:47 UTC by captain-Akshay

**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-02-02 05:58 UTC, leecalcote commented
@nwanduka., how did @captain-Akshay do?

2024-02-02 06:07 UTC, leecalcote requested changes
@Yashsharma1911 , it's unclear according to this documentation whether this silence notifications button is a per comment silencer for a silencer for all comments... in a design or for my entire user account? Does this setting only affect me or does it affect other users of this design? Do I need to own the design in order to use this? 

What happens if I muted, people make comments, I unmute will I receive historical notifications for comments that were placed while I had silence on?

2024-02-02 06:07 UTC, leecalcote commented on content/en/meshmap/designer/comments/comment-notificationBell.png
Thanks for this. Two issues:

1) poor quality screenshot.
2) let's have pleasant, positive sample interactions.

2024-02-02 06:07 UTC, leecalcote commented on content/en/meshmap/designer/comments/_index.md
> +Customize your notification preferences to mute emails for comments on your design. When this feature is enabled, you won't receive email notifications for new comments on your design. This can be us
You don't "mute emails", you "mute notifications" or "mute email notifications".

2024-02-02 06:07 UTC, leecalcote commented on content/en/meshmap/designer/comments/_index.md
> +Customize your notification preferences to mute emails for comments on your design. When this feature is enabled, you won't receive email notifications for new comments on your design. This can be us
"with this feature enabled"... no. Please change to "With notifications for new comments silenced, ..."

2024-02-02 06:07 UTC, leecalcote commented on content/en/meshmap/designer/comments/_index.md
> +Customize your notification preferences to mute emails for comments on your design. When this feature is enabled, you won't receive email notifications for new comments on your design. This can be us
"you won't receive email notifications for new comments on your design." - what about existing comments and new threaded added?

@captain-Akshay, buckle down a description of the logic here - describe the behavior in various scenarios / under various conditions.

2024-02-02 06:07 UTC, leecalcote commented
@captain-Akshay you can do better. And I expect you to do better.

2024-02-02 06:08 UTC, leecalcote commented
@nwanduka, it seems that you might have missed this review. The comments that I've made could / should be made by you as either the first reviewer or the writer of this PR.

2024-02-02 08:11 UTC, nwanduka commented
> @nwanduka, it seems that you might have missed this review. The comments that I've made could / should be made by you as either the first reviewer or the writer of this PR.

I started a review and didn't realize I hadn't submitted it. I was honestly confused when I kept getting the request to review the PR. All the while I was thinking to myself, "is no one else seeing the comment I left?" Now I know why 🤦🏽‍♀️
![image](https://github.com/layer5io/docs/assets/122698422/c84ed21e-a689-4cf6-9fa0-bd28d4dea471)

2024-02-06 22:30 UTC, Yashsharma1911 commented
> @Yashsharma1911 , it's unclear according to this documentation whether this silence notifications button is a per comment silencer for a silencer for all comments... in a design or for my entire user account? Does this setting only affect me or does it affect other users of this design? Do I need to own the design in order to use this?
> 
> What happens if I muted, people make comments, I unmute will I receive historical notifications for comments that were placed while I had silence on?

These are good questions and yes, this doc doesn't answer all of these questions, @captain-Akshay I'll help here with updating this doc

2024-02-06 22:36 UTC, Yashsharma1911 commented on content/en/meshmap/designer/comments/comment-notificationBell.png
+1

2024-02-09 15:10 UTC, iArchitSharma commented
@Yashsharma1911 @captain-Akshay @nwanduka added draft label please remove this when your finished with your changes

2024-02-16 13:34 UTC, captain-Akshay commented
![image](https://github.com/layer5io/docs/assets/59491379/f755d18f-4755-4409-b8ca-bc478ce6b245)

2024-02-18 15:37 UTC, nwanduka approved these changes
Quite an improvement from the first draft. The content looks good to me 👍🏽.

How about the image? Did you change the comment in the screenshot to a more positive one? If that's done, then I think we're set to get this merged.

2024-03-01 14:00 UTC, iArchitSharma requested changes
It's good for merging once the image is repositioned.

2024-03-01 14:00 UTC, iArchitSharma commented on content/en/meshmap/designer/comments/_index.md
> +<img src="./comment-notificationBell.png" alt="Turn Off notification from comments in designer" style="width:auto">
can you please place the image above **What Muting Affects:**

2024-03-01 14:02 UTC, iArchitSharma approved these changes
did it myself, good to merge!

2024-03-04 04:09 UTC, merged