Published slides to Layer5 docs
layer5io/docs pull request #220
Opened 2024-02-21 21:06 UTC by nwanduka

**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-02-25 13:51 UTC, vishalvivekm commented
@nwanduka 

Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

2024-02-26 12:17 UTC, nwanduka commented on content/en/cloud/security/images/Slide42.svg
Done

2024-02-28 13:26 UTC, iArchitSharma requested changes

2024-02-28 13:26 UTC, iArchitSharma commented on content/en/cloud/getting-started/getting-started-with-layer5-account.md
>  To sign in to Layer5 Cloud, navigate to <https://cloud.layer5.io/login>. Use your new credentials to sign in. In case you have signed up with OAuth provider, you will be redirected to the provider's
wrong url change it to` https://meshery.layer5.io/login`

2024-02-28 13:26 UTC, iArchitSharma commented on content/en/cloud/getting-started/getting-started-with-layer5-account.md
>  To sign up for an account on Layer5 Cloud, navigate to <https://cloud.layer5.io/signup>.
change the url to - https://meshery.layer5.io/registration

2024-02-28 13:26 UTC, iArchitSharma commented on content/en/cloud/getting-started/support.md
> +1. Go to the Layer5 Cloud [login page](https://cloud.layer5.io/login).
change this too - https://meshery.layer5.io/login

2024-02-28 13:46 UTC, nwanduka commented on content/en/cloud/getting-started/getting-started-with-layer5-account.md
>  To sign in to Layer5 Cloud, navigate to <https://cloud.layer5.io/login>. Use your new credentials to sign in. In case you have signed up with OAuth provider, you will be redirected to the provider's
Done for all

2024-03-05 18:45 UTC, iArchitSharma approved these changes
Thanks @nwanduka

2024-03-05 18:45 UTC, merged