Restructure of roles and permission pages
layer5io/docs pull request #223
Opened 2024-02-28 16:34 UTC by iArchitSharma

With this PR all default roles pages will be under Roles and default permission pages will be under Reference section

![image](https://github.com/layer5io/docs/assets/74408634/9b5b57bf-8c3c-489e-8fa0-15906534a0f2)
![image](https://github.com/layer5io/docs/assets/74408634/9abd213d-6dce-4da4-95db-9ded7c8adcdf)

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-03-04 11:30 UTC, vishalvivekm commented
@iArchitSharma Let's discuss this on Websites's call today 6:30 PM IST. Let's add this as an agenda item into the meeting minutes

2024-03-06 06:21 UTC, leecalcote requested changes

2024-03-06 06:21 UTC, leecalcote commented on content/en/cloud/security/roles/team-roles.md
> -title: Default Roles
Default needs to be mentioned, like I said earlier.

2024-03-06 13:29 UTC, iArchitSharma commented on content/en/cloud/security/roles/provider-admin-roles.md
actually they do help with the visual organization and structured layout, ill add the images in cards too

2024-03-06 14:59 UTC, merged