Add workflow and keys spreadsheet
layer5io/docs pull request #225
Opened 2024-03-01 00:23 UTC by Yashsharma1911

**Notes for Reviewers**

This PR fixes #

This PR adds generate keys workflow to generate and dump the spreadsheet and also adds spreasheet

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-03-01 11:09 UTC, iArchitSharma commented
Thanks for the new workflow @Yashsharma1911 
I've added the table in Reference page - https://deploy-preview-225--bejewelled-pegasus-b0ce81.netlify.app/cloud/reference/
![image](https://github.com/layer5io/docs/assets/74408634/e1b36ca3-7390-45fb-95d4-bb9c18c617ad)

2024-03-01 18:48 UTC, leecalcote commented
Feedback offered in today's meeting.

2024-03-01 21:58 UTC, leecalcote commented
The expected outcome of this effort looks like a single, dedicated page that lists the default roles with their default permissions (and has a link / info tip to how a docs page on how to customize them) and that perms table should look like this - 
<img width="822" alt="Screenshot 2024-03-01 at 3 57 55 PM" src="https://github.com/layer5io/docs/assets/7570704/60a0bdd7-e1e8-4e68-9db3-9677bf82d50f">

2024-03-06 06:20 UTC, leecalcote requested changes

2024-03-06 06:20 UTC, leecalcote commented on assets/csv/keys.csv
No.

2024-03-06 21:42 UTC, Yashsharma1911 commented on layouts/shortcodes/csvtable.html
> +{{ $p := "csv/keys.csv" }}
```suggestion
{{ $p := "data/csv/keys.csv" }}
```

2024-03-06 21:44 UTC, Yashsharma1911 commented on data/csv/keys.csv
> +Filter,View Filters,View all public and published filters of other team members and private of signed-in user,,,,,X,,,,Install extension,"INSERT INTO keychains (id, name, created_at, owner) VALUES ('
```suggestion
Filters,View Filters,View all public and published filters of other team members and private of signed-in user,,,,,X,,,,Install extension,"INSERT INTO keychains (id, name, created_at, owner) VALUES ('Install extension','View Filters', NOW(), uuid_nil())",df41c45f-7c73-49c2-a055-0584fdcec1c1,"INSERT INTO keys (id, keychain_id, category, subcategory, function, description, created_at, owner) VALUES ('df41c45f-7c73-49c2-a055-0584fdcec1c1','Install extension','Catalog Management','Filter','View Filters','View all public and published filters of other team members and private of signed-in user', NOW(), uuid_nil())",X,TRUE

```

2024-03-06 23:38 UTC, Yashsharma1911 commented
Outside of assets directory it is giving issue @iArchitSharma , please see if you can fix and merge after that

2024-03-07 12:31 UTC, iArchitSharma commented
@Yashsharma1911 we should remove csv from data directory
![image](https://github.com/layer5io/docs/assets/74408634/9e17436c-258f-4379-b9f2-655794b446a7)

2024-03-07 12:59 UTC, iArchitSharma commented
@Yashsharma1911 lets put the csv back to assets directory for now
i have changes location in shortcode to `assets/data/keys.csv`

2024-03-07 18:53 UTC, merged

2024-03-07 18:55 UTC, Yashsharma1911 commented
@iArchitSharma here are a few more things that can be improved:

1. Default permissions page description (it can be more expressive).
1. Audit and correct the incorrect checks for “User” role.
1. Update customizable info with exact doc on how to customise permission maybe step by step guide, instead of redirecting user to a page which describes “what are keychains” instead of how to customise it.

I’m moving forward with PR, please consider updating these in your next PR.