Add docs for white-labeling-logo
layer5io/docs pull request #248
Opened 2024-05-03 13:28 UTC by ritiksaxena124

This PR adds the doc for how to white label a logo.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-05-05 16:21 UTC, vishalvivekm commented
@ritiksaxena124 Let's discuss this on Websites's call. 
Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

2024-05-06 18:58 UTC, leecalcote requested changes

2024-05-06 18:58 UTC, leecalcote commented on content/en/cloud/miscellaneous/_index.md
> +title: Miscellaneous
@ritiksaxena124 @iArchitSharma please move this to the existing white-label section.

2024-05-06 18:58 UTC, leecalcote commented
"how to white label a logo" - no. 

"how to customize Layer5 Cloud with your own logo" - yes.

2024-05-08 03:32 UTC, leecalcote commented
@iArchitSharma ....

2024-05-13 07:02 UTC, iArchitSharma commented
@ritiksaxena124 let me know when its complete

2024-05-14 12:42 UTC, leecalcote commented on content/en/cloud/miscellaneous/_index.md
> +title: Miscellaneous
@iArchitSharma please move this to the existing white-label section.

2024-05-21 05:55 UTC, Yashsharma1911 commented
This needs a rewrite, @iArchitSharma I'm closing this

2024-05-21 05:55 UTC, closed without merging