Add new page for webhooks
layer5io/docs pull request #254
Opened 2024-05-21 06:50 UTC by Yashsharma1911

**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-05-21 11:38 UTC, iArchitSharma commented
@Yashsharma1911 Its not complete right?

2024-05-22 22:02 UTC, leecalcote requested changes

2024-05-22 22:02 UTC, leecalcote commented on content/en/cloud/self-hosted/customizing-webhooks.md
> +| Meshmap Entitlement Notification  | [https://hook.us1.make.com/mvv3ka2p1kbsvx3kuh4phqivlqohlat5](https://hook.us1.make.com/mvv3ka2p1kbsvx3kuh4phqivlqohlat5) | Sends an email notification to the use
This is Playground and Book, too, no?

2024-05-22 22:02 UTC, leecalcote commented on content/en/cloud/self-hosted/customizing-webhooks.md
> +| Signup Request Notification | [https://hook.us1.make.com/h7plpgs7me4o1mjj8uebmjmq8v23o5qj](https://hook.us1.make.com/h7plpgs7me4o1mjj8uebmjmq8v23o5qj) | Sends an update email upon signup request ap
Is this also event registration or is that not listed, @Yashsharma1911?

2024-06-07 12:15 UTC, Yashsharma1911 commented on content/en/cloud/self-hosted/customizing-webhooks.md
> +| Signup Request Notification | [https://hook.us1.make.com/h7plpgs7me4o1mjj8uebmjmq8v23o5qj](https://hook.us1.make.com/h7plpgs7me4o1mjj8uebmjmq8v23o5qj) | Sends an update email upon signup request ap
No we don't send the email for event registration right now, it is only for signup request

2024-06-07 12:22 UTC, Yashsharma1911 commented on content/en/cloud/self-hosted/customizing-webhooks.md
> +| Meshmap Entitlement Notification  | [https://hook.us1.make.com/mvv3ka2p1kbsvx3kuh4phqivlqohlat5](https://hook.us1.make.com/mvv3ka2p1kbsvx3kuh4phqivlqohlat5) | Sends an email notification to the use
The hooks we are using here are used in cloud, I think hook for book will be in website? I'm not sure for the case if we want to document that too.

2024-06-07 13:30 UTC, Yashsharma1911 commented
No other change required, I'll add more incase I missed.

pending item
- [ ] Write doc on how user can customize these hooks

2024-06-07 13:31 UTC, Yashsharma1911 commented on content/en/cloud/self-hosted/customizing-webhooks.md
> +## Customize and add your own custom webhook
```suggestion
## Customize and add your own custom webhook (Upcoming Feature)
```

2024-06-07 13:31 UTC, merged