fix #278 Unable to scroll through left sidebar
layer5io/docs pull request #281
Opened 2024-06-18 12:04 UTC by preyanshu

**Notes for Reviewers**

This PR fixes #278 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
-  Yes, I signed my commits.

2024-06-19 10:16 UTC, Ashparshp approved these changes
LGTM!!

2024-06-19 10:58 UTC, iArchitSharma requested changes
@preyanshu, first of all, thank you so much for this. However, your changes introduced a bug in the mobile view. Please fix it!
![image](https://github.com/layer5io/docs/assets/74408634/71666da0-e17f-4a2e-99b9-9eb96445ac0f)

2024-06-19 11:03 UTC, preyanshu commented
> @preyanshu, first of all, thank you so much for this. However, your changes introduced a bug in the mobile view. Please fix it! ![image](https://private-user-images.githubusercontent.com/74408634/341041492-71666da0-e17f-4a2e-99b9-9eb96445ac0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTUyMzMsIm5iZiI6MTcxODc5NDkzMywicGF0aCI6Ii83NDQwODYzNC8zNDEwNDE0OTItNzE2NjZkYTAtZTE3Zi00YTJlLTk5YjktOWViOTY0NDVhYzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZjQ2YTdiZTAyMWRhNDZjNDU1NGM4YWEzZjFlZGNkNDI4MWVlNDE1OGYxYjk0NDBiZjE1NmRjNDZjMTc2MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dY4QVYGal6URym_OTFE4SgG56_ZyVLobwMnH4Kgxtuc)

yaaa i,ll check whats wrong

2024-06-19 11:07 UTC, Ashparshp commented
@iArchitSharma Apologies for missing that!! @preyanshu, please fix it!!

2024-06-19 11:31 UTC, GaganpreetKaurKalsi requested changes
Hey @preyanshu, could you fix the bottom scrollbar issue as well in this PR which was mentioned in the issue. Minor layout fix.

![image](https://github.com/layer5io/docs/assets/54144759/9cf3ba2e-4d4d-42a0-bb4a-47d6ed37ca31)

Also the scrollbar edges are getting hidden when at the extreme corners. Could you take a look at that?
<img width="500" alt="image" src="https://github.com/layer5io/docs/assets/54144759/eb7b883b-96f2-4c05-a3fe-f06edcbd0344">

2024-06-19 11:36 UTC, preyanshu commented
> Hey @preyanshu, could you fix the bottom scrollbar issue as well in this PR which was mentioned in the issue. Minor layout fix.
> 
> ![image](https://private-user-images.githubusercontent.com/54144759/341049707-9cf3ba2e-4d4d-42a0-bb4a-47d6ed37ca31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTcyMDgsIm5iZiI6MTcxODc5NjkwOCwicGF0aCI6Ii81NDE0NDc1OS8zNDEwNDk3MDctOWNmM2JhMmUtNGQ0ZC00MmEwLWJiNGEtNDdkNmVkMzdjYTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MmVmMDJmMDMwM2JhOWJiYWQ5MjViYmM5YmRiZWE4NDdhZDAzMzMxZDMxNjFhYTZlYmIwY2UxYTNlMmU0OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_-E84ETFI4DwiTPz7ni9bftNjTG-tM7aA90GJhjSAo)
> 
> Also the scrollbar edges are getting hidden when at the extreme corners. Could you take a look at that? <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/54144759/341050859-eb7b883b-96f2-4c05-a3fe-f06edcbd0344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTcyMDgsIm5iZiI6MTcxODc5NjkwOCwicGF0aCI6Ii81NDE0NDc1OS8zNDEwNTA4NTktZWI3Yjg4M2ItOTZmMi00YzA1LWEzZmUtZjA2ZWRjYmQwMzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NWVhOWE4OWU3OTQ1OGViOWYwOWI5Mjg1MzcyZDNjZGIxOWRlMWNhYjlmMDVjNTc2NDQ3NDI0ZjgyMGE0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v9yMGNwcKAqafLjzCxLFlK7xC4r-u74GLvfUSGZc_fo">

so expected behaviour is that there should be no bottom scrolling bar?

2024-06-19 12:01 UTC, GaganpreetKaurKalsi commented
> > Hey @preyanshu, could you fix the bottom scrollbar issue as well in this PR which was mentioned in the issue. Minor layout fix.
> > ![image](https://private-user-images.githubusercontent.com/54144759/341049707-9cf3ba2e-4d4d-42a0-bb4a-47d6ed37ca31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTcyMDgsIm5iZiI6MTcxODc5NjkwOCwicGF0aCI6Ii81NDE0NDc1OS8zNDEwNDk3MDctOWNmM2JhMmUtNGQ0ZC00MmEwLWJiNGEtNDdkNmVkMzdjYTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MmVmMDJmMDMwM2JhOWJiYWQ5MjViYmM5YmRiZWE4NDdhZDAzMzMxZDMxNjFhYTZlYmIwY2UxYTNlMmU0OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_-E84ETFI4DwiTPz7ni9bftNjTG-tM7aA90GJhjSAo)
> > Also the scrollbar edges are getting hidden when at the extreme corners. Could you take a look at that? <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/54144759/341050859-eb7b883b-96f2-4c05-a3fe-f06edcbd0344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTcyMDgsIm5iZiI6MTcxODc5NjkwOCwicGF0aCI6Ii81NDE0NDc1OS8zNDEwNTA4NTktZWI3Yjg4M2ItOTZmMi00YzA1LWEzZmUtZjA2ZWRjYmQwMzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NWVhOWE4OWU3OTQ1OGViOWYwOWI5Mjg1MzcyZDNjZGIxOWRlMWNhYjlmMDVjNTc2NDQ3NDI0ZjgyMGE0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v9yMGNwcKAqafLjzCxLFlK7xC4r-u74GLvfUSGZc_fo">
> 
> so expected behaviour is that there should be no bottom scrolling bar?

Yes, since the content won't be overflowing on the x-axis

2024-06-19 13:07 UTC, preyanshu commented
hey guys @iArchitSharma @Ashparshp @GaganpreetKaurKalsi can u check this now is it okkay ?

2024-06-19 13:23 UTC, preyanshu commented
hey guys @iArchitSharma @Ashparshp @GaganpreetKaurKalsi can u check this if its okkay?

2024-06-21 04:51 UTC, iArchitSharma approved these changes
Thanks LGTM now

2024-06-21 04:53 UTC, merged

2024-06-21 06:07 UTC, GaganpreetKaurKalsi commented on assets/scss/_styles_project.scss
> +
Hiding the helm table contents because of this css. Unable to scroll through the whole table contents.
![image](https://github.com/layer5io/docs/assets/54144759/fde42e45-7b06-425f-ab7f-a05f9ae7a1ad)

2024-06-21 06:12 UTC, iArchitSharma commented on assets/scss/_styles_project.scss
> +
@GaganpreetKaurKalsi thanks for pointing it out and yes please