[Feat] Add Workspace Administrator and Workspace Manager roles documentation
layer5io/docs pull request #304
Opened 2024-06-28 13:35 UTC by dragon-slayer875

**Notes for Reviewers**

This PR adds documentation for the workspace administrator and workspace manager roles.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-06-28 13:41 UTC, dragon-slayer875 commented
- [ ] Need to add page that shows the list of all available keys
- [ ] Need to update images

2024-06-28 19:41 UTC, leecalcote requested changes
The graphic in the SVG still denotes these new roles as "Future Roles"

2024-07-01 07:14 UTC, Yashsharma1911 commented
Thankyou for adding it

2024-07-01 07:33 UTC, Yashsharma1911 approved these changes
LGTM, after image update we can merge this

2024-07-03 04:14 UTC, leecalcote commented on content/en/cloud/security/roles/_index.md
> +**When this role is first assigned?**
```suggestion
**When is this role first assigned?**
```

2024-07-03 04:15 UTC, leecalcote commented on content/en/cloud/security/roles/_index.md
> +**When this role is first assigned?**
```suggestion
**When is this role first assigned?**
```

2024-07-03 04:15 UTC, leecalcote approved these changes

2024-07-03 04:15 UTC, merged