FIX- Dropdown in Navbar Not Visible on Hover #308
layer5io/docs pull request #315
Opened 2024-07-03 18:31 UTC by 2003Aditya

**Notes for Reviewers**

This PR fixes #308 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-07-04 09:02 UTC, Ashparshp commented
LGTM!!

2024-07-04 09:08 UTC, Ashparshp reviewed
For hover it's fine!! but for phone view it's having issues, note: it must be like as it was before..

2024-07-04 09:22 UTC, Ashparshp requested changes

2024-07-04 09:22 UTC, Ashparshp commented on assets/scss/_navbar_project.scss
> +  &:hover {
```suggestion
    @media (min-width: 768px) {
    &:hover {
      .dropdown-menu {
        display: block;
      }

      .dropdown-menu {
        transform: translate(-15%, 0rem) !important;
    }

  }
  }
```

2024-07-04 09:22 UTC, Ashparshp commented on assets/scss/_navbar_project.scss
> +    transform: translate(-15%, 0rem) !important;
```suggestion
    transform: translate(-15%, 2.5rem) !important;
```

2024-07-04 18:51 UTC, Ashparshp commented on assets/scss/_navbar_project.scss
> +    transform: translate(-15%, 0rem) !important;
@leecalcote I noticed that the !important wasn't originally necessary, and upon further testing, the dropdown behavior is functioning correctly without it. It seems someone might have added it mistakenly. Hence, we can proceed without using !important at all.

2024-07-05 02:56 UTC, 2003Aditya commented on assets/scss/_navbar_project.scss
> +    transform: translate(-15%, 0rem) !important;
I will those important then

2024-07-06 20:28 UTC, Ashparshp approved these changes
LGTM!

2024-07-08 11:35 UTC, vishalvivekm commented
@2003Aditya 
Thank you for your contribution.
Let's discuss this on Websites' call starting in 30 minutes. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

2024-07-08 13:37 UTC, 2003Aditya commented
@vishalvivekm I'm sorry I couldn't join at that time..

2024-07-11 21:21 UTC, leecalcote commented
@iArchitSharma able to review?

2024-07-22 08:48 UTC, hargunkaur286 approved these changes

2024-07-22 08:48 UTC, hargunkaur286 commented
Looks good to me!

2024-07-22 08:51 UTC, hargunkaur286 commented
@2003Aditya Thank you for your contribution. Let's discuss it in today's website meeting. Adding this as an agenda item in [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

2024-08-03 16:25 UTC, Ashparshp commented
@2003Aditya Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

Any luck?

2024-08-19 21:03 UTC, Ashparshp commented
@hargunkaur286, ready to merge?

2024-08-28 04:40 UTC, merged