Added Integrating Github with Meshery to layer5 docs
layer5io/docs pull request #330
Opened 2024-07-23 00:27 UTC by Alero-Awani

**Notes for Reviewers**

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-07-23 16:16 UTC, Yashsharma1911 requested changes

2024-07-23 16:16 UTC, Yashsharma1911 commented on content/en/cloud/getting-started/github-integration.md
> +    - A popup showing the status of the import will be bottom of the screen. You will be able to view and manage your Imported designs at the finish step.
Thankyou for adding this, we recently changed this behaviour so you can now safely say, "After import you will see on screen which files are imported and which not" I have phrased it correct but yeah I hope you get the idea

![Screenshot 2024-07-23 at 9 51 55 PM](https://github.com/user-attachments/assets/b32217f1-98ed-40ac-bb2f-707451f399a4)

2024-07-23 16:16 UTC, Yashsharma1911 commented on content/en/cloud/getting-started/github-integration.md
> +    Click **Next** to finish setting up!
This step can move on top at time for where we are explaining the enabling snapshot is optional, this is part of that step, however we can explain it more by saying, "Warning shows, if snapshot is already installed on that repo, choosing a design from repo and going to next step, will overwrite the existing snapshot workflow"

2024-07-23 16:16 UTC, Yashsharma1911 commented on content/en/cloud/getting-started/github-integration.md
> +
We can add littlre more descriptions like "You have now successfully created a github connection, finish page will give overview of past steps, if things looks great click on Finish or you can go back to step which you want to make any update again"

2024-07-23 16:16 UTC, Yashsharma1911 commented on content/en/cloud/getting-started/github-integration.md
> +
What do you think?

2024-07-23 16:16 UTC, Yashsharma1911 commented on content/en/cloud/getting-started/github-integration.md
> +On the Connections page:
I think above sentence make it clear still it would be nice you can say something
```suggestion
On the Connections page in Layer5 Cloud:
```

2024-07-26 17:30 UTC, leecalcote commented
@dusdjhyeon you're 👁️s here would be great.

2024-07-26 20:04 UTC, leecalcote commented on content/en/cloud/getting-started/github-integration.md
> +You can start the integration process from the “Dashboard” or “Extensions” page on Meshery.
No, it's not and should be written to be inclusive of Cloud.

2024-07-26 20:06 UTC, leecalcote commented on content/en/cloud/getting-started/github-integration.md
> +1. On [Meshery Dashboard](https://meshery.layer5.io/dashboard). Click on the **menu icon** on the navigation bar.
```suggestion
1. From the [Cloud Dashboard](https://meshery.layer5.io/dashboard). Click on the **menu icon** to open the global navigation menu.
```

2024-07-27 00:07 UTC, dusdjhyeon commented on content/en/cloud/getting-started/github-integration.md
> +    - Once signed in, GitHub will prompt you to select the GitHub account where you want to install the Meshery GitHub App. This account could be your personal account or an organization account you
It's a simple statement, so you can probably simplify it. 
ex) Select the GitHub account (personal or organization) where you want to install the Meshery GitHub App.

2024-07-27 00:07 UTC, dusdjhyeon commented on content/en/cloud/getting-started/github-integration.md
> +    - Copy the **API TOKEN** and add it to the secrets page of your select repository. To learn more about configuring secrets check out [Using secrets in GitHub Actions](https://docs.github.com/en/a
How about this? select -> selected

2024-07-27 10:20 UTC, Alero-Awani commented
Thank you for your reviews everyone, will make these corrections today.

2024-08-02 21:47 UTC, Yashsharma1911 commented
@Alero-Awani any update here?

2024-08-02 23:18 UTC, Alero-Awani commented on content/en/cloud/getting-started/github-integration.md
> +You can start the integration process from the “Dashboard” or “Extensions” page on Meshery.
To confirm, is it this page? [https://layer5.io/cloud-native-management/meshery/integrations](https://layer5.io/cloud-native-management/meshery/integrations)

2024-08-02 23:38 UTC, Alero-Awani commented on content/en/cloud/getting-started/github-integration.md
> +1. On [Meshery Dashboard](https://meshery.layer5.io/dashboard). Click on the **menu icon** on the navigation bar.
Why is it called Cloud Dashboard and not Meshery Dashboard.  I am a bit confused, so that I make the same mistake again.

2024-08-03 11:04 UTC, Alero-Awani commented on content/en/cloud/getting-started/github-integration.md
> +### How to Access Integrations from the Extensions Page
You are right, I will restructure it

2024-08-03 13:44 UTC, Alero-Awani commented on content/en/cloud/getting-started/github-integration.md
> +    - A popup showing the status of the import will be bottom of the screen. You will be able to view and manage your Imported designs at the finish step.
I am unable to add this change for now due to my internet

2024-08-03 19:00 UTC, Yashsharma1911 commented on content/en/cloud/getting-started/github-integration.md
> +    - A popup showing the status of the import will be bottom of the screen. You will be able to view and manage your Imported designs at the finish step.
Thanks for updating other please update this at your convenience

2024-08-03 19:08 UTC, Yashsharma1911 approved these changes
Thankyou LGTM

2024-08-03 19:12 UTC, merged