hyperlinked each role from permissions page refrence
layer5io/docs pull request #335
Opened 2024-07-27 06:06 UTC by iushdoescode

**Notes for Reviewers**

This PR fixes #
All the roles were hyperlinked to their corresponding permissions.

https://github.com/user-attachments/assets/78e15aa5-3e7c-4090-b9bc-8bb264a0813c

 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-07-28 17:44 UTC, Ashparshp commented
@iushdoescode Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-08-12 10:44 UTC, sudhanshutech commented
@iushdoescode please add this to website meeting agenda here https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit and lets discuss the progress and finalize this. Please jump in 5:30pm ist

2024-08-22 18:04 UTC, dragon-slayer875 requested changes
Please make it so that the links open in the same tab.

Also please restore the names for roles images. The current names allow us to not have to update code if we make changes to the roles.

2024-08-24 07:23 UTC, sudhanshutech commented
@iushdoescode what the progress here?

2024-09-11 00:13 UTC, leecalcote commented
@iushdoescode, checking in... it'd be great to hear an update from you on progress here.

2025-05-20 22:04 UTC, closed without merging