Integration documentation in Cloud Docs
layer5io/docs pull request #357
Opened 2024-08-27 19:56 UTC by MU5A

**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-08-28 03:47 UTC, vishalvivekm commented
Thank you @MU5A 
Will you please consider reverting changes made in `package.json` and `package-lock.json` ?

2024-08-28 05:54 UTC, MU5A commented
> Thank you @MU5A Will you please consider reverting changes made in `package.json` and `package-lock.json` ?

Okay

2024-08-28 06:05 UTC, MU5A commented
@vishalvivekm confirm now

2024-08-28 18:23 UTC, MU5A commented
@vishalvivekm Can you please review now

2024-08-29 09:36 UTC, MU5A commented
@Yashsharma1911

2024-08-31 07:36 UTC, Ashparshp commented
@MU5A, Thank you for your contribution! Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT). Please consider adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).
Here is the [meeting link](https://meet.layer5.io/websites).

2024-09-01 14:14 UTC, Yashsharma1911 commented on content/en/cloud/spaces/integrations.md
> +- **Version Control:** Keep track of all changes made to your infrastructure with GitHub’s version control capabilities.
github version control is not our feature, but having diff for snapshots yes, which we will have soon I guess
```suggestion
- **Version Control:** Keep track of all changes made to your infrastructure with GitHub’s version control capabilities.
```

2024-09-01 14:14 UTC, Yashsharma1911 commented on content/en/cloud/spaces/integrations.md
> +- **Seamless Import:** Bring in your Helm Charts, Docker Compose files, and Kubernetes manifests directly into Meshery.
```suggestion
- **Seamless Import:** Bring in your Helm Charts, Docker Compose files, Kubernetes manifests or Meshery Designs directly into Meshery.
```

2024-09-01 14:14 UTC, Yashsharma1911 commented on content/en/cloud/spaces/integrations.md
> +5. **Secure Access with Credentials:**
Link to read more about how to set up credentials or use roles

2024-09-09 10:53 UTC, MU5A commented
@Ashparshp added the link to the credentials and roles

@Alero-Awani

2024-09-20 10:42 UTC, Alero-Awani requested changes
Please add in where they can find these integrations on the UI.

2024-09-24 10:06 UTC, MU5A commented
> Please add in where they can find these integrations on the UI.

There is a link for each

2024-11-08 18:55 UTC, leecalcote commented
What are we doing with this PR, @SAHU-01 ?

2025-03-15 08:25 UTC, closed without merging

2025-03-15 08:25 UTC, ritzorama commented
Stale PR