profile details
layer5io/docs pull request #376
Opened 2024-09-24 16:32 UTC by vishalvivekm

**Notes for Reviewers**

This PR adds
![image](https://github.com/user-attachments/assets/696fd883-47b7-40bc-9335-daa83032ca7c)

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-09-26 21:38 UTC, jameshorton2337 commented on layouts/partials/navbar.html
> +                  alt="Layer5 Meshery Logo"
```suggestion
                  alt="Meshery Logo"
```

2024-09-26 21:38 UTC, jameshorton2337 commented on layouts/partials/navbar.html
> +                    alt="Layer5 Meshery Logo"
```suggestion
                    alt="Meshery Logo"
```

2024-09-26 22:06 UTC, leecalcote requested changes
Whoa, this is not good. We've just leaked an API token. Why is a token needed here? 

This specific API token is now leaked to the world and needs to be deleted from whatever account created it, @vishalvivekm

2024-09-26 22:06 UTC, leecalcote commented on layouts/partials/navbar.html
> +const tok = "eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0ltdHBaQ0k2SW5CMVlteHBZenBsT0dWbU5ERmpNeTFpWldWbUxUUmlZakV0T0dVNE1DMHpOakExTVRZeU4yTTJNakVpTENKMGVYQWlPaUpLVjFRaWZRLmV5SmhkV1FpT2x0ZExDSm
Whoa, this is not good. We've just leaked an API token. Why is a token needed here? 

This specific API token is now leaked to the world and needs to be deleted from whatever account created it, @vishalvivekm

2024-09-26 22:21 UTC, vishalvivekm commented on layouts/partials/navbar.html
> +const tok = "eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0ltdHBaQ0k2SW5CMVlteHBZenBsT0dWbU5ERmpNeTFpWldWbUxUUmlZakV0T0dVNE1DMHpOakExTVRZeU4yTTJNakVpTENKMGVYQWlPaUpLVjFRaWZRLmV5SmhkV1FpT2x0ZExDSm
```suggestion
const tok = "";
```

2024-09-26 22:25 UTC, vishalvivekm commented on layouts/partials/navbar.html
> +const tok = "eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0ltdHBaQ0k2SW5CMVlteHBZenBsT0dWbU5ERmpNeTFpWldWbUxUUmlZakV0T0dVNE1DMHpOakExTVRZeU4yTTJNakVpTENKMGVYQWlPaUpLVjFRaWZRLmV5SmhkV1FpT2x0ZExDSm
My bad, the token was already expired.
I've marked this PR as draft.

2024-09-26 22:35 UTC, leecalcote commented on layouts/partials/navbar.html
> +const tok = "eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0ltdHBaQ0k2SW5CMVlteHBZenBsT0dWbU5ERmpNeTFpWldWbUxUUmlZakV0T0dVNE1DMHpOakExTVRZeU4yTTJNakVpTENKMGVYQWlPaUpLVjFRaWZRLmV5SmhkV1FpT2x0ZExDSm
Thanks. Yes, once committed (whether merged or not), we'll need to ensure the token is no longer valid. Sounds like we're fine with this one expired now.

Why is this necessary, though?

2024-10-06 23:25 UTC, leecalcote commented
@vishalvivekm is this still "Draft"?

2024-10-07 23:31 UTC, leecalcote commented
> @vishalvivekm is this still "Draft"?

@vishalvivekm is this still "Draft"?

2024-10-08 07:49 UTC, vishalvivekm commented
> > @vishalvivekm is this still "Draft"?
> 
> @vishalvivekm is this still "Draft"?

Apologies for missing the messages, no it's ready for review.

2024-10-08 12:00 UTC, leecalcote commented on layouts/partials/navbar.html
> +          <img class="footer-logo" src="/images/logo.svg" alt="logo" />
Why was this changed? What does it have to do with the avatar?

2024-10-08 12:01 UTC, leecalcote commented on layouts/partials/navbar.html
> +          <img class="footer-logo" src="/images/logo.svg" alt="logo" />
Part of the reason that I’m asking is because I see that there is a footer logo class being used. I assume that this is the footer. Maybe the footer class needs to be renamed.

2024-10-08 12:03 UTC, leecalcote commented on layouts/partials/navbar.html
> +                  alt="Layer5 Meshery Logo"
There isn’t a Layer5 Meshery logo, just a Meshery logo.

2024-10-08 12:04 UTC, leecalcote commented on layouts/partials/navbar.html
> +    const cookies = document.cookie.split(";");
This sort of string person is never ideal. Is this what was done on the other sites, too?

2024-10-08 12:06 UTC, leecalcote commented on layouts/partials/navbar.html
> +    // Refresh the current page
Not a refresh when you’re being redirected.

2024-10-08 12:07 UTC, leecalcote commented on layouts/partials/navbar.html
> +    const CLOUD_USER_API = "https://meshery.layer5.io/api/identity/users/profile";
Why are you bothering providing a separate variable when it’s buried inside of the very same code that it is used within? This defeats the purpose of the variable.

2024-10-08 12:08 UTC, leecalcote commented on layouts/partials/navbar.html
> +  function removeCookie(cookieName) {
Simply removing the cookie, but not expiring the token is a security vulnerability.

2024-10-09 20:50 UTC, leecalcote commented
Let's get a "Sign In" button presented in the corner when an anonymous visitor opens the site. Do you agree?

<img width="745" alt="Screenshot 2024-10-09 at 3 49 02 PM" src="https://github.com/user-attachments/assets/b9047590-3610-4b2f-93b2-616bf4921815">

2024-10-09 20:57 UTC, leecalcote commented
Also, will you please put Kanvas and Cloud docs links on the left with Products on the right with avatar, like this:

<img width="1551" alt="Screenshot 2024-10-09 at 3 51 47 PM" src="https://github.com/user-attachments/assets/414321d9-902b-419e-9ca4-091a6f700d4f">

2024-10-14 09:27 UTC, Touriist commented on layouts/partials/navbar.html
> +    const cookies = document.cookie.split(";");
Yes, this is the same logic from layer5 and layer5 cloud

2024-10-14 17:52 UTC, vishalvivekm commented on layouts/partials/navbar.html
> +  console.log("visiblity change happen")
```suggestion
```

2024-10-14 17:52 UTC, vishalvivekm commented on layouts/partials/navbar.html
> +     console.log("again visible")
```suggestion
```

2024-10-15 13:08 UTC, vishalvivekm commented on layouts/partials/navbar.html
> +    const cookies = document.cookie.split(";");
yeah this from layer5.io and meshery.layer5.io

2024-10-15 14:11 UTC, vishalvivekm commented
![image](https://github.com/user-attachments/assets/2692b5f6-86e8-4855-9c9a-607d6a5ab8e9)

2024-10-16 15:34 UTC, leecalcote commented on layouts/partials/navbar.html
> +  function setupDropdown(dropdownId) {
A comment describing the function, would be great.

2024-10-16 15:35 UTC, leecalcote commented on layouts/partials/navbar.html
> +  function removeCookie(cookieName) {
Use https://meshery.layer5.io/logout in addition to killing the cookie.

2024-10-16 15:57 UTC, leecalcote requested changes
@Vivek Vishal, the following pertain to both Safari and Chrome:

1. the app grid menu is bouncing around.
2. in this recording the cursor style is not consistently "pointer", although in other tests is seems fine.
3. the app grid should darken in color on hover.

https://github.com/user-attachments/assets/1b893308-b20e-4d23-9158-ef1d32ccd562

2024-10-16 15:59 UTC, leecalcote commented
Each app button should be of equal size.

2024-10-16 16:03 UTC, leecalcote commented
Is [this javascript](https://github.com/layer5io/docs/blob/8a45bf897639145e7c28572f3392ea94fc5d6f15/layouts/partials/navbar.html#L133-L155) really needed? CSS ::active doesn't cut it?

2024-10-21 15:40 UTC, merged