[UI] Dynamically adding front-matter to documentation pages
layer5io/docs pull request #379
Opened 2024-09-30 07:12 UTC by SAHU-01

**Notes for Reviewers**

This PR fixes #89

- It adds front-matter to respective documented pages sharing the subscription tier this feature is available to.
- This is done dynamically with populating data from the pricing-list workflow and based on the data received, a go script adds the front-matter to their respective documented pages.

<img width="1491" alt="image" src="https://github.com/user-attachments/assets/254e48d9-f4c6-43e5-a624-8890bdb3c05f">

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-09-30 22:35 UTC, lekaf974 commented on .github/workflows/pricing-list.yml
> +        uses: actions/checkout@v2
```suggestion
        uses: actions/checkout@v4
```

2024-09-30 22:36 UTC, lekaf974 commented on .github/workflows/pricing-list.yml
> +        uses: actions/setup-go@v2
```suggestion
        uses: actions/setup-go@v5
```

2024-09-30 22:38 UTC, lekaf974 commented on .github/workflows/pricing-list.yml
> +          # You may need to implement a polling mechanism here to check the status of the other workflow
Could we consider that the other workflow trigger this one once done ?

2024-09-30 22:39 UTC, lekaf974 commented on .github/workflows/pricing-list.yml
> +          git pull origin master
What the reason to pull master since a previous step is already doing a checkout ?

2024-09-30 22:42 UTC, lekaf974 commented on update_frontmatter.go
> +	jsonFile, err := ioutil.ReadFile("pricing_data.json")
From where the file is coming ?

Could we also use a environment variable instead of hardcoded value for the file name ?

2024-09-30 22:54 UTC, lekaf974 commented on update_frontmatter.go
> +			for i, part := range urlParts {
I'd rather put this logic in a separate method with a `extractHah` to make code more readable and to remove the comment

2024-09-30 22:54 UTC, lekaf974 commented on update_frontmatter.go
> +			for _, part := range urlParts {
same `buildPath`

2024-09-30 23:44 UTC, lekaf974 commented on update_frontmatter.go
> +		frontMatterEnd := strings.Index(contentStr, "---")
same here having a method with proper name for readability

2024-09-30 23:44 UTC, lekaf974 commented on update_frontmatter.go
> +		hashPattern := strings.ReplaceAll(urlHash, "-", "[-\\s]")
same here having a method with proper name for readability

2024-10-06 23:26 UTC, leecalcote commented
Suggested changes accepted.

2024-10-07 03:34 UTC, SAHU-01 commented on .github/workflows/pricing-list.yml
> +          git pull origin master
The reason for pulling from master after the checkout step is because the first workflow (which generates the pricing-data.json) pushes changes to the repository, so when the current workflow runs, it needs to pull the updated data to ensure it has the latest pricing-data.json. This ensures the front matter is updated based on the most recent pricing information generated by the other workflow.

2024-10-07 03:39 UTC, SAHU-01 commented on update_frontmatter.go
> +	jsonFile, err := ioutil.ReadFile("pricing_data.json")
This file is added from the  "generate-pricing-list.yml" workflow call.

Yes, we can absolutely use an environment variable, I'll add one, Thanks!

2024-10-07 03:41 UTC, SAHU-01 commented on .github/workflows/pricing-list.yml
> +          # You may need to implement a polling mechanism here to check the status of the other workflow
Yes, we can have the other workflow trigger this one when it's done, rather than relying on a polling mechanism.

2024-10-07 11:42 UTC, lekaf974 requested changes

2024-10-07 11:56 UTC, lekaf974 commented
@sudhanshutech 

I did reviews on go script but could you review the html css part I'm less comfortable on this

2024-10-07 11:57 UTC, SAHU-01 commented on update_frontmatter.go
> +	// Group entries by documentation URL
Sure, I'll get rid of all the comments, Thanks!

2024-10-09 02:53 UTC, leecalcote commented
It's coming along!

2024-10-14 05:20 UTC, vishalvivekm commented
@SAHU-01 
will you push these changes ( with the not working svgs): 
https://www.youtube.com/watch?v=L2bG-kfR5u4&t=660s

2024-10-21 01:29 UTC, vishalvivekm commented
@SAHU-01 
Let's discuss the recent changes and update on the item today, during the website call at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-10-21 11:14 UTC, vishalvivekm commented
> @SAHU-01 Let's discuss the recent changes and update on the item today, during the website call at 5:30 PM IST (7:00 AM CT).
> 
> Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

adding

2024-10-21 15:37 UTC, SAHU-01 commented
This flowchart explains how the workflows are working: https://playground.meshery.io/extension/meshmap?mode=design&design=cbb68338-be01-4e0c-b833-3b88c024ca61

2024-10-22 03:26 UTC, leecalcote commented on .github/workflows/feature-list.yml
> +              repo: 'meshery-extensions-packages',
What's the purpose of running the workflow over here? @vishalvivekm @SAHU-01 @jerensl

2024-10-22 15:04 UTC, SAHU-01 commented on .github/workflows/feature-list.yml
> +              repo: 'meshery-extensions-packages',
This workflow fetches the integration sheet and parses the csv and gives us a json file, additionally, it filters out and returns rows of the sheet in json that we need to map, i.e. if a feature on the sheet has been documented or has been marked to be displayed on pricing page.

2024-10-23 11:41 UTC, lekaf974 commented
@SAHU-01 do you have done a diagram that explain those github workflows dependencies?

2024-10-29 13:19 UTC, leecalcote approved these changes

2024-10-29 13:20 UTC, merged