Update README.md
layer5io/docs pull request #391
Opened 2024-10-15 08:51 UTC by Manvendra2000

Consolidated the pointers into a single line and improved the documentation's readability.

**Notes for Reviewers**

This PR fixes #
Consolidated the pointers into a single line and improved the documentation's readability.

Signing off as Manvendra [mzealpro@gmail.com]

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [✅ ] Yes, I signed my commits.

2024-10-17 01:49 UTC, leecalcote requested changes
Thanks for this, @Manvendra2000. Will you please instead remove this image and copy/paste the text, checkmarks, and community icon from https://github.com/layer5io/layer5/blob/master/README.md ?

2024-10-17 07:55 UTC, Manvendra2000 commented
> Thanks for this, @Manvendra2000. Will you please instead remove this image and copy/paste the text, checkmarks, and community icon from https://github.com/layer5io/layer5/blob/master/README.md ?

For Sure! [here ](https://github.com/layer5io/docs/pull/391/commits/6d095130d7bbb5e2801fab280f0426f44ca81058)it is @leecalcote

2024-10-17 14:22 UTC, leecalcote reviewed
Thanks!

2024-10-17 14:22 UTC, leecalcote commented on README.md
> +<div class="flex">
is flex used on the original readme? I'd be surprised if GFMD supported this.

2024-10-17 15:20 UTC, leecalcote commented
@Manvendra2000 https://layer5io.slack.com/archives/C019426UBNY/p1729177173523569

2024-10-17 15:55 UTC, Manvendra2000 commented on README.md
> +<div class="flex">
Hey @leecalcote I have removed class="flex" in the new commit. Apart from that the in the doc in meshary/readme.md line 313 below is the screenshot, flex is being used. should I work on this issue ![image](https://github.com/user-attachments/assets/35688803-284a-4eba-9161-2c5eddcdafb2)

2024-10-21 01:26 UTC, vishalvivekm commented
@Manvendra2000 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-10-21 01:34 UTC, Manvendra2000 commented
@vishalvivekm I have added the the issue to Agenda of meeting.

2024-10-21 11:12 UTC, vishalvivekm commented on README.md
> +✔️ <em><strong>Watch</strong></em> community <a href="https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0">meeting recordings</a>.<br />
```suggestion
✔️ <em><strong>Watch</strong></em> community <a href="https://www.youtube.com/Layer5io?sub_confirmation=1">meeting recordings</a>.<br />
```

2024-10-25 12:36 UTC, merged