[Security] keys and keychains
layer5io/docs pull request #40
Opened 2023-11-03 12:35 UTC by sudhanshutech

**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-11-03 13:01 UTC, leecalcote commented on content/en/cloud/security/keys.md
> +  Keys are a fundamental component of our cloud system, playing a crucial role in access control and permissions management. They are essential for ensuring that users have the appropriate access to
This paragraph needs to be rewritten.

2023-11-03 20:23 UTC, leecalcote commented on content/en/cloud/security/keys.md
> +In our cloud system, a "key" is a unique identifier used to grant or restrict access to specific functionalities or features. Keys have a significant impact on access control, as they determine what
No: "in our cloud system".

2023-11-03 20:24 UTC, leecalcote commented on content/en/cloud/security/keys.md
> +- It provides the clearest indication of the key's purpose.
"It" what?

2023-11-03 20:27 UTC, leecalcote requested changes
Can keys be modified? Who can create them? How do I request new keys? 

What are they used for specifically? Are they grouped? Are they the same across all Meshery Servers? Across all Remote Providers? 

What types of keys are there? View, Edit, Delete, other? Where are keys enforced? When are keys updated? Does Cloud and Server have to be of the same version in order for keys to work? 

How do I review all keys? or view them by group? Can I create new groups of keys, if so how do I assign these to users? Can I assign keys directly? Can I assign keys to teams?

@theBeginner86, you can take over this PR.

2023-11-03 20:27 UTC, leecalcote commented on content/en/cloud/security/keys.md
> +- The description provides a more detailed explanation of the key's role.
Include an example.

2023-11-05 15:16 UTC, leecalcote commented
@theBeginner86, you can take over this PR.

2023-11-11 04:53 UTC, leecalcote commented
@theBeginner86 comfortable taking this on?

2023-11-12 17:45 UTC, theBeginner86 commented
> @theBeginner86, you can take over this PR.

Updated 👍

2023-11-17 13:34 UTC, theBeginner86 commented
I'm pressing forward here...

If there are issues or improvements, please let me know I'll come back and fix them. 👍

2023-11-17 13:34 UTC, merged