[Docs] Images are displayed too large #410
layer5io/docs pull request #416
Opened 2024-11-29 16:54 UTC by Ravnoor12

**Notes for Reviewers**

This PR fixes #410 
Component/kanvas-doc

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [✔️] Yes, I signed my commits.

2024-11-29 19:05 UTC, leecalcote requested changes

2024-11-29 19:05 UTC, leecalcote commented on content/en/kanvas/visualizer/images/interactive-terminal-sequence-diagram.svg
@Ravnoor12 don't delete this image.

2024-11-29 19:05 UTC, leecalcote commented on assets/scss/_content_project.scss
> +    width: 20%;
Thanks. We need something more consideration that this, however. Look across the pages and their images. Make sure that the logic here is dynamic in nature so that this sizing works ubiquitously.

2024-11-29 19:06 UTC, leecalcote commented on package.json
Remove this change, please. You can submit this in a separate PR.

2024-11-29 19:30 UTC, Ravnoor12 commented on package.json
sure I will revert the changes that you said. Also I will once again test to check if logic is dynamic in nautre and other images on different pages are not getting affected.

2024-12-06 02:41 UTC, Ravnoor12 commented
@leecalcote Kindly take a look, I have reverted the image and the package.json changes back. Additionally, I verified that the changes in width are working fine and none of the other images across the other pages are effected. 
Best regards and Thanks

2024-12-08 16:19 UTC, leecalcote requested changes
12 files are changed in this PR. Remove all unnecessary changes not pertinent to this PR.

2024-12-11 20:13 UTC, closed without merging