feat: add a new footer which replaces the existing one
layer5io/docs pull request #46
Opened 2023-11-04 11:14 UTC by 35C4n0r

- The footer data and links are stored in hugo.toml
- styling has been added to _content_projects.scss.
- Breakpoints have been added.

**Notes for Reviewers**

This PR fixes #15 and #44 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-11-04 11:48 UTC, 35C4n0r commented
@leecalcote the PR is up for review.

2023-11-04 11:51 UTC, 35C4n0r commented
@leecalcote ps: not a part of the issue #15, but should I add the code for the scrollbar too?
![image](https://github.com/layer5io/docs/assets/70096901/05292aeb-7e48-497f-b93e-399e84911484)

2023-11-04 12:33 UTC, iArchitSharma requested changes
@35C4n0r can you please change the logo svg to the one that is being used in header

2023-11-04 19:07 UTC, 35C4n0r commented
> @35C4n0r can you please change the logo svg to the one that is being used in header

@iArchitSharma updated the logo

2023-11-05 03:49 UTC, leecalcote commented
> > @35C4n0r can you please change the logo svg to the one that is being used in header
> 
> @iArchitSharma updated the logo

@ritiksaxena124 to confirm.

2023-11-05 03:50 UTC, leecalcote commented
> @leecalcote ps: not a part of the issue #15, but should I add the code for the scrollbar too?
> ![image](https://user-images.githubusercontent.com/70096901/280464122-05292aeb-7e48-497f-b93e-399e84911484.png)

Sounds great. Yes.

2023-11-05 04:19 UTC, 35C4n0r commented
@leecalcote added the scrollbar :)

2023-11-05 05:09 UTC, ritiksaxena124 commented
> > @35C4n0r can you please change the logo svg to the one that is being used in header
> 
> @iArchitSharma updated the logo

@35C4n0r you are referencing the logo we have in the header, which is good. Could you please update the Twitter logo to "X"

2023-11-05 05:53 UTC, 35C4n0r commented
Ok @ritiksaxena124 , keeping only the `https://layer5.io/subscribe`
But to include the X logo we would need to update to font awesome package to v6.4.2
Can you please guide me how to update this version.
I've tried running `go get github.com/FortAwesome/Font-Awesome@latest`, but i'm getting some error after that.

2023-11-05 07:06 UTC, ritiksaxena124 commented
> Ok @ritiksaxena124 , keeping only the `https://layer5.io/subscribe` But to include the X logo we would need to update to font awesome package to v6.4.2 Can you please guide me how to update this version. I've tried running `go get github.com/FortAwesome/Font-Awesome@latest`, but i'm getting some error after that.

Instead of using FontAwesome icons you can use the SVG

2023-11-05 15:15 UTC, leecalcote commented
> > Ok @ritiksaxena124 , keeping only the `https://layer5.io/subscribe` But to include the X logo we would need to update to font awesome package to v6.4.2 Can you please guide me how to update this version. I've tried running `go get github.com/FortAwesome/Font-Awesome@latest`, but i'm getting some error after that.
> 
> Instead of using FontAwesome icons you can use the SVG

Yes, please.

2023-11-06 02:32 UTC, 35C4n0r commented
@ritiksaxena124 replaced fa with the SVGs

2023-11-06 08:41 UTC, iArchitSharma requested changes
@35C4n0r well done with the logo
also add space b/w `2023 Copyright` and shift **Privacy** and **Terms** in right side just as it is in layer5.io
![image](https://github.com/layer5io/docs/assets/74408634/8a9cacec-ba66-4106-bddb-700d4799442f)

2023-11-06 12:07 UTC, saurabh100ni commented
Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) to present it in the Website Meet today at 6:30 pm IST/7:00 am CT

2023-11-06 12:53 UTC, 35C4n0r commented
> layer5.io



> @35C4n0r well done with the logo also add space b/w `2023 Copyright` and shift **Privacy** and **Terms** in right side just as it is in layer5.io ![image](https://user-images.githubusercontent.com/74408634/280641506-8a9cacec-ba66-4106-bddb-700d4799442f.png)

@iArchitSharma fixed this.

2023-11-06 15:12 UTC, iArchitSharma commented
> add space b/w `2023 Copyright`

nice but you didn't added space b/w **2023** and **Copyright**

2023-11-06 15:39 UTC, 35C4n0r commented
@iArchitSharma wierd bug, but it looks fine on my local
![image](https://github.com/layer5io/docs/assets/70096901/cbda6cca-ce17-48e6-a1a2-2c64e4847d10)

I'll see how i can fix this

2023-11-06 15:54 UTC, 35C4n0r commented
@iArchitSharma there we go, string concatenation works.

2023-11-06 15:59 UTC, iArchitSharma approved these changes
@35C4n0r Good job, LGTM //
@ritiksaxena124

2023-11-06 20:55 UTC, leecalcote reviewed
Thank you, @35C4n0r, @iArchitSharma.

Will you move the footer css into a separate .scss file, and import into _content_project.scss?

2023-11-07 03:52 UTC, 35C4n0r commented
@leecalcote done :)

2023-11-07 06:42 UTC, ritiksaxena124 requested changes

2023-11-07 06:42 UTC, ritiksaxena124 commented on layouts/partials/footer.html
> +                    maintainer of cloud naative standards. Maker of Meshery, the cloud native manager.</p>
```suggestion
                    maintainer of cloud native standards. Maker of Meshery, the cloud native manager.</p>
```

2023-11-07 06:42 UTC, ritiksaxena124 commented on layouts/partials/footer.html
> +                                <button class="footer-button" title="Subscribe" type="submit">Subscribe</button>
Change the text color to white 
Image from layer5.io
![image](https://github.com/layer5io/docs/assets/51539117/4068af1a-316d-42a5-8cf2-d66d63fabf4c)

Image from deploy preview of your PR
![image](https://github.com/layer5io/docs/assets/51539117/692f4299-1139-401b-8371-dd9485a17cfc)

2023-11-07 06:42 UTC, ritiksaxena124 commented on assets/scss/footer.scss
> +      background: #fbfbfd;
Use the variables for colors, if there is no entry will you make a new one

2023-11-07 15:40 UTC, 35C4n0r commented on layouts/partials/footer.html
> +                    maintainer of cloud naative standards. Maker of Meshery, the cloud native manager.</p>
Probably need changes too.
https://github.com/layer5io/layer5/blob/61a55eea2cfd0a56eae65c2e0c57efb292881418/src/assets/discuss/html/footer.html#L38

2023-11-08 17:19 UTC, leecalcote approved these changes
Excellent, @35C4n0r 🥇

2023-11-08 17:21 UTC, leecalcote commented
Ideally, in all of our site's footers, we'll using SVGs with vectors inside (not SVGs with rasterized PNGs inside).

2023-11-09 02:51 UTC, coder12git requested changes

2023-11-09 02:51 UTC, coder12git commented on assets/scss/footer.scss
> +      max-height: 250px;
Please use `rem` instead of `px`

2023-11-09 02:51 UTC, coder12git commented on hugo.toml
> +		icon = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiBpZD0iTGF5ZXJfMSIgeD0iMCIgeT0iMCIgdmVyc2lvbj0iMS4xIiB
Use SVGs with vectors, you can directly  import those icons SVGs in `assets/images` directory and can add a link here.

2023-11-09 02:59 UTC, coder12git commented
@35C4n0r footer is not completely responsive.

![Screenshot 2023-11-09 082527](https://github.com/layer5io/docs/assets/108334168/95166349-16c4-4633-aaa2-37d751ec7189)

Ideally it should look same, in mobile view as we have for `layer5.io` sites, check below screenshots:

![Screenshot 2023-11-09 082628](https://github.com/layer5io/docs/assets/108334168/2b1581e9-0a61-45a2-9468-f2ef3fcc0026)
![Screenshot 2023-11-09 082609](https://github.com/layer5io/docs/assets/108334168/317d58c6-e615-41e7-890b-1dee25974ee1)

2023-11-09 04:03 UTC, leecalcote commented
Hang in there, @35C4n0r. You're doing some good work.

2023-11-11 06:00 UTC, 35C4n0r commented on assets/scss/footer.scss
> +      max-height: 250px;
Do i need to replace all the px with rems??

2023-11-11 06:00 UTC, 35C4n0r commented
> @35C4n0r footer is not completely responsive. Also the description text and some other texts used here is 'open-sans' instead of 'Qanleas Soft`.
> 
> ![Screenshot 2023-11-09 082527](https://user-images.githubusercontent.com/108334168/281601654-95166349-16c4-4633-aaa2-37d751ec7189.png)
> 
> Ideally it should look same, in mobile view as we have for `layer5.io` sites, check below screenshots:
> 
> ![Screenshot 2023-11-09 082628](https://user-images.githubusercontent.com/108334168/281601883-2b1581e9-0a61-45a2-9468-f2ef3fcc0026.png) ![Screenshot 2023-11-09 082609](https://user-images.githubusercontent.com/108334168/281601919-317d58c6-e615-41e7-890b-1dee25974ee1.png)

@coder12git made the css more, responsive will be pushing the code soon.

2023-11-11 08:39 UTC, 35C4n0r commented on hugo.toml
> +		icon = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiBpZD0iTGF5ZXJfMSIgeD0iMCIgeT0iMCIgdmVyc2lvbj0iMS4xIiB
Sure.

2023-11-11 11:41 UTC, 35C4n0r commented
Pushed the code, @coder12git kidly give a re-review

2023-11-11 14:28 UTC, coder12git commented on assets/scss/_variables_project.scss
> +$font-qanelas: "Qanelas Soft", sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial,  "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
```suggestion
$font-qanelas: "Qanelas Soft", "Open Sans", sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial,  "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
```

2023-11-11 14:32 UTC, coder12git commented
@35C4n0r great work you did. Everything looks good to me, just remove that extra spacing from bottom (in mobile view).
![Screenshot 2023-11-11 195925](https://github.com/layer5io/docs/assets/108334168/a6ab3bf1-8320-4aa8-88f9-98dd1dcc8d27)

2023-11-11 17:42 UTC, 35C4n0r commented
@coder12git @coder12git apparently it wasn't a bug related to footer, maybe background overflow https://github.com/layer5io/docs/pull/33 ?? I've fixed it now.

2023-11-11 20:17 UTC, iArchitSharma commented
@35C4n0r good work there, was the scrollbar supposed to be that way?

2023-11-12 07:50 UTC, abhijeetgauravm commented
Hey @35C4n0r  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2023-11-12 09:28 UTC, coder12git approved these changes

2023-11-12 09:30 UTC, coder12git commented
@35C4n0r thanks, @leecalcote this PR is good to merge now 🚀

2023-11-12 12:35 UTC, 35C4n0r commented
Nope, that is because of this https://github.com/layer5io/docs/pull/46#issuecomment-1806875029
will need to discuss a better way to resolve this, that overflow in not a part of HTML??? Most probably because of background image, not sure.
![image](https://github.com/layer5io/docs/assets/70096901/a04cdc77-b34c-4b98-bf31-cb64f438fa9d)

2023-11-14 14:45 UTC, leecalcote commented
Thanks for sticking with this, @35C4n0r

2023-11-14 14:45 UTC, merged