feat: add hotkey access for searchbar
layer5io/docs pull request #79
Opened 2023-11-18 23:19 UTC by phukon

### Notes for Reviewers

This PR adds feature #66 

-  Hotkeys: `ctrl + k` or `⌘ + k` (Mac)
- The root html file has been modified.
- Hotkey focus preference is given to the Header search bar.
- styles added in the root html.

**Footnote:**
Followed the _README.md_ to run the dev server I noticed there's an issue arise with the `make docker` command due to an undefined rule in the `Makefile`.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-11-19 00:35 UTC, leecalcote commented
Only `/` is needed as the shortcut key.

2023-11-19 05:25 UTC, phukon commented
Made changes.

2023-11-19 08:41 UTC, abhijeetgauravm commented
Hey @phukon  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2023-11-19 14:03 UTC, leecalcote commented
The only hotkey that we're seeking to add here is that of `/`. You can remove any code pertaining to `ctl` and `k`

2023-11-19 16:20 UTC, leecalcote approved these changes
Thanks for this PR, @phukon 👏

2023-11-19 19:11 UTC, phukon commented
- Squashed commits and rebased my current branch.
- Changed variable names for clarity.

2023-11-20 19:25 UTC, leecalcote requested changes

2023-11-20 19:25 UTC, leecalcote commented on layouts/_default/baseof.html
>      {{ partial "head.html" . }}
This script isn’t necessary. Can you implement without this script?

2023-11-20 20:02 UTC, phukon commented on layouts/_default/baseof.html
>      {{ partial "head.html" . }}
Sure. 
Please note that these lines were present before I implemented my modifications.

2023-11-21 22:14 UTC, leecalcote commented on layouts/_default/baseof.html
>      {{ partial "head.html" . }}
@phukon, oh, I see. It would be most conducive to review, if you only include changes that you've made. You might need to turn off your local linter / formatter. Will you send word when you've updated this PR with only your changes?

2023-11-21 23:15 UTC, phukon commented on layouts/_default/baseof.html
>      {{ partial "head.html" . }}
@leecalcote I reverted the changes.

2023-11-23 05:46 UTC, leecalcote commented on layouts/docs/baseof.html
> +        function focusSearchBar() {
@phukon thanks. Do we need two separate scripts or can these be consolidated?

Will you please move this script into the footer - into a partial either in the footer itself or a separate partial.

Apologies for the continued requests for changes. We're nearly there.

2023-11-23 05:47 UTC, leecalcote commented on layouts/_default/baseof.html
>      {{ partial "head.html" . }}
Good work, @phukon

2023-11-23 06:08 UTC, phukon commented on layouts/docs/baseof.html
> +        function focusSearchBar() {
No worries. I did a quick fix to get more inputs. I'll make the necessary changes. Also can we add a code formatter config to keep the code style consistent?

2023-11-23 06:50 UTC, leecalcote commented on layouts/docs/baseof.html
> +        function focusSearchBar() {
Yes, sounds good to me. Ideally, one can be pulled from another Layer5 project.

2023-11-23 07:18 UTC, phukon commented
@leecalcote  The commit history was getting messy. Hence discarded the 4 redundant commits. Will make a new PR now.

2023-11-23 07:33 UTC, phukon commented
'hotkey func' given it's own partial and now lives in the footer

2023-11-23 14:22 UTC, leecalcote commented
@phukon are you in the community Slack?

2023-11-23 19:54 UTC, phukon commented
> @phukon are you in the community Slack?

thanks for the heads up.. I just joined.

2023-11-23 20:39 UTC, merged